# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkLogDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkLogDemo
  pod 'NetworkLogger', :path => "../"

  target 'NetworkLogDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkLogDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
