//
//  LogComposer.swift
//  NetworkLogger
//
//  Created by Sunil Sharma on 17/01/19.
//  Copyright © 2019 Sunil Sharma. All rights reserved.
//

import Foundation

internal class LogComposer {
    
    func getResponseLog(from logData: NLLogData) ->  String {
        
        var responseStr = "\n\(getBoundry(for: "Response"))\n"
        responseStr += "\(getIdentifierString(logData.identifier))"
        responseStr += "\nResponse for Request\n\(logData.urlRequest.cURL)\n"
        
        let jsonUtils = JSONUtils.shared
        
        if let metaData = logData.response {
            responseStr += "\n\(getBoundry(for: "Response Metadata"))\n\n"
            responseStr += getResponseMetaData(response: metaData) + "\n"
            responseStr += "\n\(getBoundry(for: "Response Metadata End"))\n"
        }
        
        if let error = logData.error {
            responseStr += "\n\(getBoundry(for: "Response Error"))\n\n"
            responseStr += error.localizedDescription + "\n"
            responseStr += "\n\(getBoundry(for: "Response Error End"))\n"
        }
        
        if let data = logData.receivedData {
            responseStr += "\n\(getBoundry(for: "Response Content"))\n\n"
            responseStr += jsonUtils.getJsonStringFrom(jsonData: data) + "\n"
            responseStr += "\n\(getBoundry(for: "Response Content End"))\n"
        }
        
        responseStr += "\n\(getBoundry(for: "Response End"))"
        return responseStr
    }
    
    func getRequestLog(from logData: NLLogData) -> String {
        let urlRequest: URLRequest = logData.urlRequest
        var urlRequestStr = ""
        urlRequestStr += "\n\(getBoundry(for: "Request"))\n"
        urlRequestStr += "\nId - \(getIdentifierString(logData.identifier))"
        urlRequestStr += "\nURL: \(urlRequest.url?.absoluteString ?? "No URL found")"
        urlRequestStr += "\nMethod: \(urlRequest.httpMethod ?? "-")"
        urlRequestStr += "\n\(urlRequest.cURL)"
        if let port = urlRequest.url?.port {
            urlRequestStr += "\nPort = \(port)"
        }
        urlRequestStr += "\nRequest Properties\n"
        urlRequestStr += "\nTimeout interval = \(urlRequest.timeoutInterval)"
        urlRequestStr += "\nMobile data access allowed = \(urlRequest.allowsCellularAccess)"
        urlRequestStr += "\nCache policy = \(urlRequest.cachePolicy.rawValue)"
        urlRequestStr += "\nNetwork service type = \(urlRequest.networkServiceType.rawValue)"
        urlRequestStr += "\nCookies will be handled = \(urlRequest.httpShouldHandleCookies)"
        urlRequestStr += "\nHTTP Pipelining will be used = \(urlRequest.httpShouldUsePipelining)"
        
        urlRequestStr += "\n\nHeaders fields\n"
        for (key, value) in urlRequest.allHTTPHeaderFields ?? [:] {
            urlRequestStr.append("\n\(key) => \(value)")
        }
        urlRequestStr += "\n\n\(getBoundry(for: "Request End"))\n"
        
        return urlRequestStr
    }
    
    private func getBoundry(for message: String) -> String {
        return "====== \(message) ======"
    }
    
    func getResponseMetaData(response: URLResponse) -> String {
        var responseStr = ""
        responseStr += "\nURL => \(response.url?.absoluteString ?? "Nil")"
        if let port = response.url?.port {
            responseStr += "\nPort => \(port)"
        }
        
        if let httpResponse = response as? HTTPURLResponse {
            responseStr += "\nStatus Code => \(httpResponse.statusCode)"
            responseStr += "\nStatus Code description => \(HTTPURLResponse.localizedString(forStatusCode: httpResponse.statusCode))"
        }
        
        responseStr += "\nMime type => \(response.mimeType ?? "Nil")"
        responseStr += "\nExpected content length => \(response.expectedContentLength)"
        responseStr += "\nText encoding name => \(response.textEncodingName ?? "Nil")"
        responseStr += "\nSuggested file name => \(response.suggestedFilename ?? "Nil")"
        
        if let httpResponse = response as? HTTPURLResponse {
            responseStr += "\n\nHeaders fields\n"
            for (key, value) in httpResponse.allHeaderFields {
                responseStr.append("\n\(key) => \(value)")
            }
        }
        
        return responseStr
    }
    
    func getIdentifierString(_ identifier: String) -> String {
        return "\(identifier) (Generated by NetworkLogger)"
    }
    
}
